//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientTest.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;id&quot;:null,&quot;command&quot;:&quot;subscribetag&quot;,&quot;isBroadcast&quot;:false,&quot;isResponce&quot;:false,&quot;parameters&quot;:null,&quot;error&quot;:0,&quot;datas&quot;:[{&quot;DisplayFullName&quot;:&quot;摄像机状态.网络状态&quot;,&quot;FullName&quot;:&quot;摄像机状态.网络状态&quot;,&quot;InstanceName&quot;:&quot;摄像机状态&quot;,&quot;ShortName&quot;:&quot;网络状态&quot;},{&quot;DisplayFullName&quot;:&quot;摄像机状态.站厅南进站闸机2_0a1798d2-9dcd-4e30-be11-41df6f996894.网络状态&quot;,&quot;FullName&quot;:&quot;摄像机状态.站厅南进站闸机2_0a1798d2-9dcd-4e30-be11-41df6f996894.网络状态&quot;,&quot;InstanceName&quot;:&quot;摄像机状态&quot;,&quot;ShortName&quot;:&quot;站厅南进站闸机2_0a1798d2-9dcd-4e30-be11-41df6f996894.网络状态&quot;},{&quot;DisplayFullName&quot;:&quot;摄像机状态.小站台应急照明配电室外_d954595f-59d0-4ea8-8cbe-dc [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 大json_2_ {
            get {
                return ResourceManager.GetString("大json(2)", resourceCulture);
            }
        }
    }
}
